name: liri-calculator
version: '0.1.0'
summary: A cross-platform material design calculator
description: A cross-platform material design calculator

grade: devel
confinement: strict

plugs:
  platform:
    interface: content
    content: liri-platform0
    target: liri-platform
    default-provider: liri-platform0

apps:
  liri-calculator:
    command: liri-app-launch $SNAP/bin/liri-calculator
    plugs:
      - x11
      - opengl
      - unity7

parts:
  liri-calculator:
    source: https://github.com/lirios/calculator
    source-type: git
    plugin: qbs
    build-attributes: ["no-system-libraries"]
    after: [liri-platform-v0.10.0]
    build-packages:
      - build-essential
      - mesa-common-dev
      - libgl1-mesa-dev
      - g++
