name: liri-terminal
version: '0.1.0'
summary: Terminal
description: Liri Terminal

grade: devel
confinement: classic

apps:
  liri-terminal:
    # Classic snap needs full path to liri-app-launch
    command: bin/liri-app-launch $SNAP/bin/liri-terminal

parts:
  liri-terminal:
    source: https://github.com/lirios/terminal
    source-type: git
    plugin: qbs
    build-attributes: ["no-system-libraries"]
    build-packages:
      - build-essential
      - mesa-common-dev
      - libgl1-mesa-dev
      - g++
    after:
      - liri-platform-v0.10.0
      - liri-platform-ext-snap-classic
