name: liri-browser
version: '0.1.0'
summary: A cross-platform material web browser
description: A cross-platform material web browser

grade: devel
confinement: strict

plugs:
  browser-sandbox:
    interface: browser-support
    allow-sandbox: true
  platform:
    interface: content
    content: liri-platform
    target: liri-platform
    default-provider: liri-platform-0-9

apps:
  liri-browser:
    command: liri-app-launch $SNAP/bin/liri-browser
    environment:
        # Workaround QtWebEngine crashing when
        # using Nouveau graphic drivers by forcing
        # the Qt xcb plugin to use software rendering:
        # https://bugreports.qt.io/browse/QTBUG-41242
        QT_XCB_FORCE_SOFTWARE_OPENGL: 1
    plugs:
      - x11
      - opengl
      - unity7
      - browser-sandbox
      - network
      - network-bind
      - pulseaudio
      - camera
      - screen-inhibit-control

parts:
  liri-browser:
    source: https://github.com/lirios/browser
    source-type: git
    plugin: qbs
    build-attributes: ["no-system-libraries"]
    build-packages:
      - build-essential
      - mesa-common-dev
      - libgl1-mesa-dev
      - g++
    after:
      - liri-platform-0-9
