name: liri-text
version: '0.1.0'
summary: A cross-platform material text editor
description: A cross-platform material text editor

grade: devel
confinement: strict

plugs:
  platform:
    interface: content
    content: liri-platform
    target: liri-platform
    default-provider: liri-platform-0-9

apps:
  liri-text:
    command: liri-app-launch $SNAP/bin/liri-text
    plugs:
      - x11
      - opengl
      - unity7
      - home

parts:
  liri-text:
    source: https://github.com/lirios/text
    source-type: git
    plugin: qbs
    build-attributes: ["no-system-libraries"]
    build-packages:
      - build-essential
      - mesa-common-dev
      - libgl1-mesa-dev
      - g++
    stage-packages:
      - sqlite3
    after: [liri-platform-0-9]
