name: liri-files
version: '0.1.0'
summary: File manager
description: Liri file manager

grade: devel
confinement: classic

plugs:
  platform:
    interface: content
    content: liri-platform0
    target: liri-platform
    default-provider: liri-platform0

apps:
  liri-files:
    # Classic snap needs full path to liri-app-launch
    command: bin/liri-app-launch $SNAP/bin/liri-files
    plugs:
      - x11
      - opengl
      - unity7
      - home

parts:
  app:
    source: https://github.com/lirios/files
    source-type: git
    plugin: qbs
    build-attributes: ["no-system-libraries"]
    build-packages:
      - build-essential
      - mesa-common-dev
      - libgl1-mesa-dev
      - g++
      - libtag1-dev
    stage-packages:
      - libtag1v5
    after:
      - liri-platform-v0.10.0
      - liri-platform-ext-snap-classic
